{"type":"auditAdvisory","data":{"resolution":{"id":1556,"path":"node-fetch","dev":false,"optional":false,"bundled":false},"advisory":{"findings":[{"version":"1.7.3","paths":["node-fetch"]}],"id":1556,"created":"2020-09-10T17:55:53.926Z","updated":"2020-09-10T17:55:53.926Z","deleted":null,"title":"Denial of Service","found_by":{"link":"","name":"Unknown","email":""},"reported_by":{"link":"","name":"Unknown","email":""},"module_name":"node-fetch","cves":["CVE-2020-15168"],"vulnerable_versions":"< 2.6.1 || >= 3.0.0-beta.1 < 3.0.0-beta.9","patched_versions":">=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9","overview":"Node Fetch did not honor the size option after following a redirect, which means that when a content size was over the limit, a FetchError would never get thrown and the process would end without failure.\n\nFor most people, this fix will have a little or no impact. However, if you are relying on node-fetch to gate files above a size, the impact could be significant, for example: If you don't double-check the size of the data after fetch() has completed, your JS thread could get tied up doing work on a large file (DoS) and/or cost you money in computing.","recommendation":"Upgrade to version 2.6.1 or 3.0.0-beta.9","references":"- https://github.com/node-fetch/node-fetch/security/advisories/GHSA-w7rc-rwvf-8q5r","access":"public","severity":"low","cwe":"CWE-400","metadata":{"module_type":"","exploitability":3,"affected_components":""},"url":"https://npmjs.com/advisories/1556"}}}
